#!/usr/bin/env python
import argparse
import os

from src.task1 import task1
from src.task2 import task2
from src.task3 import task3
from src.task4 import task4


def main():
    parser = argparse.ArgumentParser(description='mlap_prog')
    parser.add_argument('task_num', action='store', choices=[1, 2, 3, 4], type=int,
                        help='Task number: 1, 2, 3 or 4')
    parser.add_argument('input_file', action='store',
                        help='Path to input file')

    args = parser.parse_args()
    task_num = args.task_num
    input_file = args.input_file

    print 'Task', task_num
    print 'Input file is:', input_file, '\n'

    if not os.path.exists(input_file):
        print("Input file doesn't exist!")
        return

    if task_num is 1:
        task1(input_file)
    elif task_num is 2:
        task2(input_file)
    elif task_num is 3:
        task3(input_file)
    elif task_num is 4:
        task4(input_file)
    else:
        print "Unknown task number should be 1,2, 3 or 4!"


if __name__ == '__main__':
    main()
